# fly.toml app configuration file generated for my-blog
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-blog"
primary_region = "nrt"  # Tokyo region (가장 가까운 리전)

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
